
IMAP_URL = 'imap.gmail.com'
CONFIG_START_INDEX = 1
CONFIG_END_INDEX = 10 
CONFIG_DIR = "upwork"
JOB_CHECK_FILE = 'job_check.txt'
EMAIL_CHECK_FILE = 'email_check.txt'
EMAIL_LIST_FILE = 'email_list.txt'

LOGIN_PATH = 'https://www.upwork.com/ab/account-security/login'
SIGNUP_PATH = 'https://www.upwork.com/nx/signup/?dest=home'
REGISTER_PATH = 'https://www.upwork.com/nx/create-profile/welcome'
MOST_RECENT_PATH = 'https://www.upwork.com/nx/find-work/most-recent'

SIGNUP_TIMES = 10
SIGNUP_INTERVAL_TIME = 5
AUTOBID_INTERVAL_TIME = 2

FIXED_BUDGET_DURATION_LESS_1 = 3000
FIXED_BUDGET_DURATION_1_3 = 6000
FIXED_BUDGET_DURATION_3_6 = 10000
FIXED_BUDGET_PERCENTAGE_LESS_1 = 0.9
FIXED_BUDGET_PERCENTAGE_1_3 = 0.8
FIXED_BUDGET_PERCENTAGE_3_6 = 0.8
FIXED_BUDGET_PERCENTAGE_MORE_6 = 0.7

# MESSAGES

SUCCESS_SIGNUP = 200
ERROR_EMAIL_VERIFY = 101
ERROR_RESUME = 102
ERROR_PHOTO = 103
ERROR_SIGNUP = 199
ERROR_BROWSER = 123
INSUFFICIENT_CONNECTS = 131

UNKNOWN_ERROR = 500